### ISSUE TITLE
Dúvida Retorno Boleto PHP

### ISSUE THREAD

**Issue by augustoparis** [manoelcampos/retorno-boletophp#2]
Boa Tarde Manoel, tudo bem?
Me chamo Augusto e estive olhando o seu projeto. Estou precisando implementar essas funcionalidades na empresa em que trabalho. No seu projeto, você só fez a implementação do arquivo de retorno do banco Bradesco?

**Comment by manoelcampos** [comment]
Eu implementei os padrões CNAB 240 e 400
que testei com Banco do Brasil, não Bradesco.

Se o Bradesco usa algum destes padrões,
então está pronto, basta usar algum dos exemplos disponibilizados e testar.

2014-09-19 21:45 GMT+01:00 Augusto da Cunha Paris notifications@github.com
:
