### ISSUE TITLE
Organização dos exemplos no projeto

### ISSUE THREAD

**Issue by vndmtrx** [manoelcampos/retorno-boletophp#3]
Devido ao fato de os arquivos da biblioteca e dos exemplos estarem em branches diferentes, existe a possibilidade de que os mesmos fiquem defasados em relação um ao outro.

Minha sugestão é colocar os exemplos em um nível abaixo do nível da bilioteca, como a seguir:
- retorno-boletophp
  - exemplos
  - retorno-boleto-php

Sendo que na segunda pasta, ficam os arquivos da biblioteca propriamente ditos, e permitindo que a branch mapeie as alterações em ambos ao mesmo tempo.

**Comment by manoelcampos** [comment]
Fala Rolim, tudo bem?
Então, tinha pensado nisso, mas o problema é que disponibilizando o projeto no repositório do composer, os exemplos vão juntos. Quem baixar os fontes direto do github com certeza desejará ver os exemplos para entender como funciona. Mas quem vai usar pelo composer é porque já sabe como faz e vai implementar seu próprio código para usar o projeto.

Por isso optei por deixar os exemplos em uma branch separada para não encher o projeto do usuário de código inutilizável. Concorda?

**Comment by vndmtrx** [comment]
Faz sentido. Eu estou organizando um outro projeto meu em C dessa forma, de forma que eu tenha um Makefile raiz que compila os exemplos e os testes, e dentro da pasta do código do projeto em si, outro Makefile só para compilar o código-fonte. Esse Makefile, inclusive, é referenciado no Makefile de nível mais alto.

No entanto, eu concordo com o esquema de branching pra separar o projeto dos exemplos, eu só não uso por tender a não atualizar o mesmo com a alteração da biblioteca principal.
